#!/usr/bin/env sh
# ---------------------------------------------------------------------------------------------------------------------
# BSPWM RESOURCE CONFIGURATION
#
# This script initialises BSPWM. Desktops, behavior, rules, as well as color preferences are set.
# ---------------------------------------------------------------------------------------------------------------------

# Workaround for Java GUIs to render properly.
wmname LG3D

# Configuration and Theme
bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Convenience function that gets the hex color of a given x-resource.
xrdbq() {
  xrdb -query | grep "^\*\.$1:" | cut -f 2
}

bspc config normal_border_color "$(xrdbq background-dark)"
bspc config active_border_color "$(xrdbq background-dark)"
bspc config focused_border_color "$(xrdbq accent)"
bspc config presel_feedback_color "$(xrdbq background-select)"

unfunction xrdbq

# Window rules.
bspc rule -r "*"
bspc rule -a Zathura state=tiled
bspc config external_rules_command "$(command -v bspwm_external_rules)"

# Start the status bar.
launch_polybar

# Apply any per-host configurations, if applicable.
host_override -s bspwm.sh && exit

# Otherwise, apply these sane defaults.
bspc monitor primary -d 1 2 3 4 5 6 7 8 9
xwallpaper -zoom "$XDG_DATA_HOME/dotfiles/images/manjarowatch.png"
