#!/bin/sh
# -----------------------------------------------------------------------------
# BSPWM Resource Configuration
#
# This script initialises BSPWM. Desktops, behavior, rules, as well as color
# preferences are set.
# -----------------------------------------------------------------------------

# Workaround for Java GUIs to render properly.
wmname LG3D

# Configuration and Theme
bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Convenience function that gets the hex color of a given x-resource.
xrdbq() {
  xrdb -query | grep "^\*\.$1:" | cut -f 2
}

bspc config normal_border_color "$(xrdbq background-dark)"
bspc config active_border_color "$(xrdbq background-dark)"
bspc config focused_border_color "$(xrdbq accent)"
bspc config presel_feedback_color "$(xrdbq background-select)"

# Reset rules and desktops
bspc rule -r "*"

# Apply any per-host configurations, if applicable.
BSPWM_OVERRIDE="$XDG_CONFIG_HOME/dotfiles/$(hostname)/bspwm.sh"
$BSPWM_OVERRIDE > /dev/null 2>&1 && exit

# Otherwise, apply these sane defaults.
bspc monitor primary -d 1 2 3 4 5 6 7 8 9
feh \
  --no-fehbg \
  --bg-fill \
  --no-xinerama \
  "$XDG_DATA_HOME/dotfiles/images/manjarowatch.png"
