#!/bin/sh
# -----------------------------------------------------------------------------
# BSPWM Resource Configuration
#
# This script initialises BSPWM. Desktops, behavior, rules, as well as color
# preferences are set.
# -----------------------------------------------------------------------------

# Desktops per Monitor
# TODO: Configure dynamically (i.e. don't hardcode displays).
bspc monitor DP-1 -d 4 5 6
bspc monitor DP-3 -d 1 2 3
bspc monitor DP-5 -d 7 8 9

# Set Wallpaper
# TODO: Configure dynamically
# (i.e. don't hardcode path to wallpaper, select based on number of monitors)
feh \
  --no-fehbg \
  --bg-fill \
  --no-xinerama \
  "$XDG_DATA_HOME/images/manjarowatch.png"

# Workaround for Java GUIs to render properly.
wmname LG3D

# Configuration and Theme
bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

xrdbq() {
  xrdb -query | grep "^\*\.$1:" | cut -f 2
}

bspc config normal_border_color "$(xrdbq background-dark)"
bspc config active_border_color "$(xrdbq background-dark)"
bspc config focused_border_color "$(xrdbq accent)"
bspc config presel_feedback_color "$(xrdbq background-select)"

# Window Rules
bspc rule -r "*"
