#!/bin/sh
# -----------------------------------------------------------------------------
# SXIV Key Handler
#
# This is called by sxiv when activating script mode via Ctrl+X.
# The selected file(s)'s path is read into $FILE.
# -----------------------------------------------------------------------------
while read -r FILE; do
  case "$1" in
  'C-c') # Copy image to clipboard
    [ -z "$BATCH_MODE" ] || exit
    xclip -selection clipboard -target image/png "$FILE" &&
      notify-send -u low "📋 Copied to Clipboard" ;;
  'greater') # Permanently rotate image clockwise.
    mogrify -rotate 90 "$FILE" ;;
  'less') # Permanently rotate image anti-clockwise.
    mogrify -rotate 270 "$FILE" ;;
  'Delete') # Prompt for confirmation and delete image.
    confirm "Delete $FILE?" &&
      rm "$FILE" && notify-send -u low "♻️ Image deleted." ;;
  'S-Delete') # Delete image without prompt.
    rm "$FILE" && notify-send -u low "♻️ Image deleted." ;;
  *) # Undefined command.
    notify-send "❌ Undefined Command" "SXIV has no action bound to '$1'"
    exit
    ;;
  esac
  BATCH_MODE=true
done
