#!/bin/sh
# -----------------------------------------------------------------------------
# SXIV Key Handler
#
# This is called by sxiv when activating script mode via Ctrl+X.
# The selected file(s)'s path is read into $FILE.
# -----------------------------------------------------------------------------
while read -r FILE; do
  case "$1" in
    'C-c') # Copy image to clipboard
      xclip -selection clipboard -target image/png "$FILE" &&
      notify-send -u low "📋 Copied to Clipboard" ;;
    'greater') # Permanently rotate image clockwise.
      mogrify -rotate 90 "$FILE" ;;
    'less') # Permanently rotate image anti-clockwise.
      mogrify -rotate 270 "$FILE" ;;
    *) # Undefined command.
      notify-send "❌ Undefined Command" "SXIV has no action bound to '$1'" ;;
  esac
done
